### DISCUSSION TITLE
ffmpeg copy to frigate no sound

### DISCUSSION THREAD

**Discussion by mikki8** [roleoroleo/yi-hack-Allwinner-v2#1012] [Q&A]
hi guys,

played with ffmpeg for unrelated stuff with the rtsp stream of my cams.

`ffmpeg  -i rtsp://user:pass@192.168.1.2/ch0_1.h264  -acodec copy -vcodec copy -f mp4 stream.mp4`

and noticed a better video quality. tried it frigate.

```
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  #hwaccel_args: preset-intel-qsv-h264
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
  #  -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
  #  -rtsp_transport tcp
  input_args: -acodec copy -vcodec copy
  #hwaccel_args: 
  #  preset-vaapi

```

but it wont record any sound. is there any way to fix it ?
