### DISCUSSION TITLE
YiHome 2K strange banding

### DISCUSSION THREAD

**Discussion by AndreaACME** [roleoroleo/yi-hack-Allwinner-v2#1028] [General]
Hi,  I have a strange issue (maybe a bug on streraming pipeline) where the cam shows banding at random places from top to bottom of screen.

**Running from:**
Home Assistant
Core 2025.4.4
Supervisor 2025.05.5
Frontend 20250411.0

**Integration**:   Yi Home Cameras with yi-hack   0.5.1

**Installed on:**
RPI4

**YiCam version:**
Firmware Version | 0.3.3
Base Version | 12.0.51.04_202311171457
Model Suffix | y291ga
Serial Number | YFUSY94OG570VZ231121
Local Time | Sun Jun 22 19:13:37 CEST 2025
Uptime | 8d 8h 37m 48s
Load Average | 1.16 1.39 1.53
Free/Total Memory | 6416/60912 KB
Free SD Space | 52%

**HA settings for Glance Card:**

```
camera_view: auto
type: picture-glance
entities:
  - entity: binary_sensor.yihack_lounge_motion_detection
  - entity: switch.yihack_lounge_ir
  - entity: switch.yihack_lounge_motion_detection
  - entity: binary_sensor.yihack_lounge_human_detection
  - entity: switch.yihack_lounge_ai_human_detection
  - entity: switch.yihack_lounge_save_video_on_motion
camera_image: camera.yihack_lounge_cam
entity: camera.yihack_lounge_cam
title: Lounge
```

- Preview on HA is always OK:
![image](https://github.com/user-attachments/assets/7ed2f012-0757-47ce-a34c-66ac0d95b01e)
- Video saved (when activated) is always OK
- Stream preview is NOT OK:
![image](https://github.com/user-attachments/assets/e6522e05-0ed5-43c4-8cbd-dc62c8f0a695)
- Downloaded snap requested is always OK
![snapshot_camera_yihack_lounge_cam_22_06_2025, 19_23_41](https://github.com/user-attachments/assets/a1b6b45d-5934-4167-97a3-c7e14e1be580)

Any help with this?
