### DISCUSSION TITLE
Should the MQTT offline message be bundled with a motion_stop?

### DISCUSSION THREAD

**Discussion by AndreasBVB** [roleoroleo/yi-hack-Allwinner-v2#434] [Ideas]
Thank you very much for bringing to us this amazing Yi Cam hack series. I am new to this and running into a situation:
 - the camera detected a motion and the HA motion sensor is ON
 - the camera got restarted while the HA motion sensor is still on (1min off_delay as far as I can tell)
 - the HA motion sensor stays on after the reboot and be on for ever if no further physical motion detected, waiting for a motion_stop MQTT message

I resolved this by creating an automation triggered by an offline MQTT message, which then publishes a faux motion_stop MQTT to the same camera topic. I had to create such an automation for each camera. Wondering if it's cleaner the motion_stop can be bundled with the offline status from the developer side. Thanks again!
```
alias: Yi1080_YZYZYZ_Offline
description: ''
trigger:
  - platform: mqtt
    topic: YiCam/1080_YZYZYZ/status
    payload: offline
condition: []
action:
  - service: mqtt.publish
    data:
      topic: YiCam/1080_YZYZYZ/motion_detection
      payload: motion_stop
mode: single
```
