### DISCUSSION TITLE
CCTV / video surveillance software recommendations?

### DISCUSSION THREAD

**Discussion by chrbar11** [roleoroleo/yi-hack-Allwinner-v2#679] [Q&A]
Hi, I'm a newbie with camera and video surveillance.

Currently I've installed some Yi cameras with Cloud disable, videos are saved to SD card and copied to NAS via FTP.

I'd like to install, ideally  as docker, a video surveillance software system on my NAS ([OMV](https://www.openmediavault.org/)), and use it to record and manage videos from my Yi cameras.

I found [ZoneMinder](https://cloud.zoneminder.com/), sounds great, but I don't know if it's the best choice for me!

Do you have any recommended CCTV software systems that you already use with Yi cameras?

Will CCTV software be able to use the motion detection features included in Yi cameras?

Thank you so much :)
Chris

**Comment by Giuserver** [comment]
hi,
you mean streaming or just for see mp4 videos saved in your NAS?

**Comment by chrbar11** [comment]
Both if possible :)

My first goal is a solution that records video on motion (and sound) detection), secures it on my NAS, and allows me to easely browse recordings from my NAS (for better file playback).
Ideally I'd like to add human/object detection service later.

Yi firmware with Yi-Hack (with Cloud disabled) can do this by recording videos to SD card and copying them to NAS via FTP.
All that's missing is a great recordings browser solution and a notification feature.

So I figure it would be better if CCTV software handles the whole process and allows me to browse the information intuitively.

But in another way I think it might be safer if the videos are first saved locally on SD card, in case the wireless network fails!
I don't know what is the best configuration!!

My second goal is to be able to watch the live stream if I need to check something.

This is my first experience with CCTV, and I will be grateful for all your advice :)

**Reply by decimoseptimo** [reply]
frigate?

**Comment by uklatt** [comment]
I use frigage as docker container on QNAP NAS.
With additional Google Coral AI dongle it's a nice and open source solution.
Uwe

**Reply by gcarabetta** [reply]
Which Frigate version? Can you share your Frigate config?
Thanks

**Comment by nemonoid** [comment]
I use the Motioneye software on a Raspberry Pi 4.  
As the operating system I use DietPi instad of Raspbian (it has a nice option to install an optimized version of Motioneye), and I record on a USB connected SSD.

PRO:
- Very stable set-up, no problems at all. 
- With only one YI Home1080p camera the Raspberry Pi 4 CPU and RAM usage is low.
- TRIM is enabled on the SSD so it can last a long time (more than micro SD cards)
- videos are being written in real time to the RPI4, so if someone immediately steals the camera, everything is still recorded on the RPI4 (I tested it).

CONS:
- Motioneye does not yet support audio recording
- With this setup the motion detection is done by Motioneye on the RPI4, doesn't use the motion detection done by the camera.
- there is some small but constant network traffic between the YI camera and the RPI4.

**Comment by uklatt** [comment]
@gcarabetta 
Here is my actual config for the YI camera. I detect birds and record small clips when a bird shows up...
I use the coral USB, but it works also with CPU detection. I use also the integrated go2rtc.
My system runs as docker container inside of proxmox lxc. The intel cpu offers hardware decoding of h264 video.
My camera is a y21ga with firmware 0.3.1
Frigate is version 0.13.2

Uwe

```
go2rtc:
  streams:
    YI:
      - rtsp://192.168.x.y/ch0_0.h264
      - "ffmpeg:rtsp_cam"        

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  width: 320
  height: 320

logger:
  default: info
  logs:
    frigate.event: debug

environment_vars:
  TZ: CET

birdseye:
  enabled: True
  quality: 1
  mode: continuous

record:
  enabled: true
  sync_recordings: True
  events:
    retain:
      default: 3

snapshots:
  clean_copy: false
  enabled: True
  timestamp: False
  bounding_box: False
  crop: True
  retain:
    default: 3
    mode: active_objects

live:
  height: 1080
  quality: 1

ui:
  live_mode: mse
  use_experimental: False

timestamp_style:
  position: "tl"
  format: "%d.%m.%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1
  effect: shadow

telemetry:
  version_check: false

cameras:
  YI:
    enabled: true 
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/YI
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 60

    detect:
      enabled: true
      fps: 5
      max_disappeared: 25
      stationary:
        interval: 5
        threshold: 50
    
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 5
        post_capture: 15
        retain:
          default: 3
          mode: motion

    objects:
      track:
        - bird
      filters:
        bird:
          min_area: 2000
    motion:
      frame_height: 150

```
