### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by mAsHERbtm** [roleoroleo/yi-hack-Allwinner-v2#49]
I have question about integration with Home Assistant

1. How to properly add a camera to the Home Assistant so that all sensors are visible (motion detection, human detection, baby crying).
2. How add a camera so that the motion sensor is displayed with camera view.

I was able to add a camera to HA but I do not have a motion sensor in view.
After adding sensors in the binary sensor, only the motion sensor works (all sensors from the application level are enabled: http://ip_camera:8080/?page=camera_settings). 
Not working Human Detection and Baby Crying.

my file: **configuration.yaml**

```
stream:
ffmpeg:
camera:
  - platform: ffmpeg
    name: yi_hack_v4
    input: -rtsp_transport tcp -i rtsp://ip_camera/ch0_0.h264

binary_sensor:
  - platform: mqtt
    state_topic: "yicam/motion_detection"
    name: "yicam_motion_sensor"
    payload_on: "motion_start"
    payload_off: "motion_stop"
    device_class: motion
  - platform: mqtt
    state_topic: "yicam/ai_human_detection"
    name: "yicam_human_sensor"
    payload_on: "human_start"
    payload_off: "human_stop"
    device_class: motion
  - platform: mqtt
    state_topic: "yicam/baby_crying"
    name: "yicam_baby_sensor"
    payload_on: "crying"
    device_class: sound
```
