### ISSUE TITLE
MQTT sound detection events

### ISSUE THREAD

**Issue by mcanteri** [roleoroleo/yi-hack-Allwinner-v2#713]
Hello,
I cannot see any sound detection event coming from any of the two cameras (y21ga) that I have: I am playing with the level but no differences between the 30 or 90 dB levels. 
I know the noise can be revealed because I am using FFmpeg noise in HA and it is working (sound detected, so the microphone is working) but the MQTT topic "yicam/sound_detection" and message "sound_detected" never show up.
My current configuration is:
```
mqtt:
  binary_sensor:
    - state_topic: "yicam/status"
      name: "Camera Status"
      payload_on: "online"
      payload_off: "offline"
      qos: 1
      unique_id: camera_status
    - state_topic: "yicam/motion_detection"
      name: "Motion Detection"
      payload_on: "motion_start"
      payload_off: "motion_stop"
      qos: 1
      off_delay: 10
      unique_id: motion_detection
    - state_topic: "yicam/sound_detection"
      name: "Sound Detection"
      payload_on: "sound_detected"
      qos: 1
      off_delay: 10
      unique_id: sound_detection

```
And is this since the beginning of the hack version (0.2 or so) :)
Any help/guidance appreciated.
